# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170321_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_id',
            field=models.AutoField(default=1, primary_key=True),
            preserve_default=False,
        ),
    ]
