# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('url_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('total', models.FloatField(max_length=200)),
                ('street_name', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=7)),
                ('date', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_short_name', models.CharField(max_length=40)),
                ('product_name', models.CharField(max_length=200)),
                ('product_make', models.CharField(max_length=200)),
                ('product_category', models.CharField(max_length=200)),
                ('product_subcategory', models.CharField(max_length=200)),
                ('price', models.FloatField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('features', models.CharField(max_length=400)),
                ('image_link', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('product_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('subcategory_image', models.CharField(max_length=200)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Category')),
            ],
        ),
    ]
