# Generated by Django 2.0.dev20170125212659 on 2017-03-01 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_make',
            field=models.CharField(default='Sony', max_length=200),
            preserve_default=False,
        ),
    ]
