# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-21 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20170301_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_subcategory',
            field=models.CharField(default='game', max_length=200),
            preserve_default=False,
        ),
    ]
