# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-21 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_products_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Users'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
