# Generated by Django 2.0.dev20170125212659 on 2017-03-22 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20170322_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('subcategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('subcategory', models.CharField(max_length=200)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Category')),
            ],
        ),
    ]
