# Generated by Django 2.0.dev20170125212659 on 2017-03-22 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_category_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='colour',
        ),
    ]
