# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170323_2207'),
        ('product', '0008_remove_products_colour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(max_length=200)),
                ('total', models.FloatField(max_length=200)),
                ('street_name', models.CharField(max_length=200)),
                ('postcode_name', models.CharField(max_length=7)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_short_name', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=200)),
                ('product_make', models.CharField(max_length=200)),
                ('product_category', models.CharField(max_length=200)),
                ('product_subcategory', models.CharField(max_length=200)),
                ('price', models.FloatField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('image_link', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('product_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name=b'product_id',
        ),
        migrations.RemoveField(
            model_name='orders',
            name=b'user_id',
        ),
        migrations.RemoveField(
            model_name='product_option',
            name=b'product_id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name=b'category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name=b'subcategory',
            new_name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='url_name',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subcategory_image',
            field=models.CharField(default='needs_to_be_done', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Product_option',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User'),
        ),
    ]
