# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20170323_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.CharField(default='feature1 | feature2 | feature3', max_length=200),
            preserve_default=False,
        ),
    ]
